/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dhaval
 */
public class Loan extends javax.swing.JFrame {

    /**
     * Creates new form Loan
     */
    public Loan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jtxtName = new javax.swing.JTextField();
        jtxtAddress = new javax.swing.JTextField();
        jtxtAccountType = new javax.swing.JTextField();
        jWithdrawal = new javax.swing.JTextField();
        jOverDraft = new javax.swing.JTextField();
        jDeposite = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jloantype = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jloancalculator = new javax.swing.JButton();
        jreset = new javax.swing.JButton();
        jexit = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLoanReport = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtxtLoan = new javax.swing.JTextField();
        jtxtInterest = new javax.swing.JTextField();
        jtxtMonth = new javax.swing.JTextField();
        jtxtMonthlyPayment = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jPanel2.setForeground(new java.awt.Color(102, 255, 51));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("MS Gothic", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 255, 51));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Full Name");

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("MS Gothic", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 255, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Address");
        jLabel5.setToolTipText("");

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("MS Gothic", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 255, 51));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Account Type");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("MS Gothic", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 255, 51));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Deposite.?");

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("MS Gothic", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 255, 51));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Withdrawal.?");

        jtxtName.setBackground(new java.awt.Color(0, 0, 0));
        jtxtName.setFont(new java.awt.Font("MS Gothic", 1, 18)); // NOI18N
        jtxtName.setForeground(new java.awt.Color(102, 255, 51));
        jtxtName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNameActionPerformed(evt);
            }
        });

        jtxtAddress.setBackground(new java.awt.Color(0, 0, 0));
        jtxtAddress.setFont(new java.awt.Font("MS Gothic", 1, 18)); // NOI18N
        jtxtAddress.setForeground(new java.awt.Color(153, 255, 51));
        jtxtAddress.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtAddressActionPerformed(evt);
            }
        });

        jtxtAccountType.setBackground(new java.awt.Color(0, 0, 0));
        jtxtAccountType.setFont(new java.awt.Font("MS Gothic", 1, 18)); // NOI18N
        jtxtAccountType.setForeground(new java.awt.Color(102, 255, 51));
        jtxtAccountType.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtAccountType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtAccountTypeActionPerformed(evt);
            }
        });

        jWithdrawal.setBackground(new java.awt.Color(0, 0, 0));
        jWithdrawal.setFont(new java.awt.Font("MS Gothic", 1, 18)); // NOI18N
        jWithdrawal.setForeground(new java.awt.Color(102, 255, 51));
        jWithdrawal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jWithdrawal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jWithdrawalActionPerformed(evt);
            }
        });

        jOverDraft.setBackground(new java.awt.Color(0, 0, 0));
        jOverDraft.setFont(new java.awt.Font("MS Gothic", 1, 18)); // NOI18N
        jOverDraft.setForeground(new java.awt.Color(153, 255, 51));
        jOverDraft.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jOverDraft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOverDraftActionPerformed(evt);
            }
        });

        jDeposite.setBackground(new java.awt.Color(0, 0, 0));
        jDeposite.setFont(new java.awt.Font("MS Gothic", 1, 18)); // NOI18N
        jDeposite.setForeground(new java.awt.Color(102, 255, 51));
        jDeposite.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jDeposite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDepositeActionPerformed(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("MS Gothic", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 255, 51));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("OverDraft");

        jLabel13.setBackground(new java.awt.Color(0, 0, 0));
        jLabel13.setFont(new java.awt.Font("MS Gothic", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 255, 51));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Loan Type");

        jloantype.setBackground(new java.awt.Color(0, 0, 0));
        jloantype.setFont(new java.awt.Font("MS Gothic", 1, 18)); // NOI18N
        jloantype.setForeground(new java.awt.Color(153, 255, 51));
        jloantype.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jloantype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jloantypeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jOverDraft, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jtxtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jtxtName, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jtxtAccountType, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(56, 56, 56))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jWithdrawal, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                                .addComponent(jDeposite))
                            .addContainerGap()))
                    .addComponent(jloantype, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxtName)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtAddress))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtAccountType, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jWithdrawal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDeposite)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jOverDraft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jloantype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(86, 86, 86))
        );

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jPanel3.setForeground(new java.awt.Color(153, 255, 51));

        jloancalculator.setBackground(new java.awt.Color(0, 0, 0));
        jloancalculator.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        jloancalculator.setForeground(new java.awt.Color(102, 255, 51));
        jloancalculator.setText("Loan Calculator");
        jloancalculator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jloancalculatorActionPerformed(evt);
            }
        });

        jreset.setBackground(new java.awt.Color(0, 0, 0));
        jreset.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        jreset.setForeground(new java.awt.Color(51, 255, 51));
        jreset.setText("Reset");
        jreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jresetActionPerformed(evt);
            }
        });

        jexit.setBackground(new java.awt.Color(0, 0, 0));
        jexit.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        jexit.setForeground(new java.awt.Color(153, 255, 51));
        jexit.setText("Exit");
        jexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jexitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jloancalculator, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jreset, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(357, 357, 357)
                .addComponent(jexit, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jloancalculator, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                    .addComponent(jexit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jreset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jLoanReport.setBackground(new java.awt.Color(0, 0, 0));
        jLoanReport.setColumns(20);
        jLoanReport.setFont(new java.awt.Font("MS Gothic", 0, 12)); // NOI18N
        jLoanReport.setForeground(new java.awt.Color(153, 255, 51));
        jLoanReport.setRows(5);
        jScrollPane1.setViewportView(jLoanReport);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jPanel4.setForeground(new java.awt.Color(102, 255, 51));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("MS Gothic", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 255, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Amount Of Loan");

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("MS Gothic", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 255, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Interest Rate");

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("MS Gothic", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 255, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Number Of Payments");

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("MS Gothic", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 255, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Monthly Payments");

        jtxtLoan.setBackground(new java.awt.Color(0, 0, 0));
        jtxtLoan.setFont(new java.awt.Font("MS Gothic", 0, 18)); // NOI18N
        jtxtLoan.setForeground(new java.awt.Color(102, 255, 51));
        jtxtLoan.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jtxtInterest.setBackground(new java.awt.Color(0, 0, 0));
        jtxtInterest.setFont(new java.awt.Font("MS Gothic", 0, 18)); // NOI18N
        jtxtInterest.setForeground(new java.awt.Color(102, 255, 51));
        jtxtInterest.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jtxtMonth.setBackground(new java.awt.Color(0, 0, 0));
        jtxtMonth.setFont(new java.awt.Font("MS Gothic", 0, 18)); // NOI18N
        jtxtMonth.setForeground(new java.awt.Color(102, 255, 51));
        jtxtMonth.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jtxtMonthlyPayment.setBackground(new java.awt.Color(0, 0, 0));
        jtxtMonthlyPayment.setFont(new java.awt.Font("MS Gothic", 0, 18)); // NOI18N
        jtxtMonthlyPayment.setForeground(new java.awt.Color(102, 255, 51));
        jtxtMonthlyPayment.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtMonthlyPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtMonthlyPaymentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 212, Short.MAX_VALUE)
                        .addComponent(jtxtLoan, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(172, 172, 172)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxtMonthlyPayment)
                            .addComponent(jtxtMonth, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                            .addComponent(jtxtInterest, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE))))
                .addContainerGap(432, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxtLoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxtInterest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jtxtMonthlyPayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jPanel1.setForeground(new java.awt.Color(153, 255, 51));

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("MS Gothic", 1, 48)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 255, 51));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Loan Management System");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(122, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 1204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNameActionPerformed

    }//GEN-LAST:event_jtxtNameActionPerformed

    private void jtxtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtAddressActionPerformed

    }//GEN-LAST:event_jtxtAddressActionPerformed

    private void jtxtAccountTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtAccountTypeActionPerformed

    }//GEN-LAST:event_jtxtAccountTypeActionPerformed

    private void jWithdrawalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jWithdrawalActionPerformed

    }//GEN-LAST:event_jWithdrawalActionPerformed

    private void jOverDraftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOverDraftActionPerformed

    }//GEN-LAST:event_jOverDraftActionPerformed

    private void jDepositeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDepositeActionPerformed

    }//GEN-LAST:event_jDepositeActionPerformed

    private void jloantypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jloantypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jloantypeActionPerformed

    private void jloancalculatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jloancalculatorActionPerformed
        /////////////////////////////// Loan Calculator Button ///////////////////////////////////

        /*
        if(jtxtName.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "You Must Enter Full Name", "Loan System", JOptionPane.INFORMATION_MESSAGE);
        }

        else
        {
            interest = Double.parseDouble(jtxtName.getText());
            String Name = String.format(jtxtName.getText());

        }

        ////////////////////////////////////////////////////////////////////////

        if(jtxtAddress.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "You Must Enter Your Adress", "Loan System", JOptionPane.INFORMATION_MESSAGE);
        }

        else
        {
            interest = Double.parseDouble(jtxtAddress.getText());
            String Address = String.format(jtxtAddress.getText());

        }

        ////////////////////////////////////////////////////////////////////////

        if(jtxtAccountType.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "You Must Enter Your Account Type", "Loan System", JOptionPane.INFORMATION_MESSAGE);
        }

        else
        {
            interest = Double.parseDouble(jtxtAccountType.getText());
            String Accounttype = String.format(jtxtAccountType.getText());

        }

        ////////////////////////////////////////////////////////////////////////

        if(jWithdrawal.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "You Must Enter Yes Or No In Withdrawal Section", "Loan System", JOptionPane.INFORMATION_MESSAGE);
        }

        else
        {
            interest = Double.parseDouble(jWithdrawal.getText());
            String Withdrawal = String.format(jWithdrawal.getText());

        }

        ////////////////////////////////////////////////////////////////////////

        if(jDeposite.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "You Must Enter Yes Or No In Deposite Section", "Loan System", JOptionPane.INFORMATION_MESSAGE);
        }

        else
        {
            interest = Double.parseDouble(jDeposite.getText());
            String Deposite = String.format(jDeposite.getText());

        }

        //////////////////////////////////////////////////////////////////////

        if(jOverDraft.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "You Must Enter Yes Or No In Deposite Section", "Loan System", JOptionPane.INFORMATION_MESSAGE);
        }

        else
        {
            interest = Double.parseDouble(jOverDraft.getText());
            String Overdraft = String.format(jOverDraft.getText());

        }
        */

        //////////////////////////////////////////////////////////////////////////
        String MonthlyPayment = String.format(jtxtMonthlyPayment.getText());

        if(jtxtLoan.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "You Must Enter The Amount Of Loan", "Loan System", JOptionPane.INFORMATION_MESSAGE);
        }

        else
        {
            loan = Double.parseDouble(jtxtLoan.getText());
            String Balance = String.format(jtxtLoan.getText());

        }

        ////////////////////////////////////////////////////////////////////////

        if(jtxtInterest.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "You Must Enter The Interest Rate", "Loan System", JOptionPane.INFORMATION_MESSAGE);
        }

        else
        {
            interest = Double.parseDouble(jtxtInterest.getText());
            String Interest = String.format(jtxtInterest.getText());

        }

        ////////////////////////////////////////////////////////////////////////

        if(jtxtMonth.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "You Must Enter The Number Of Payment", "Loan System", JOptionPane.INFORMATION_MESSAGE);
        }

        else
        {
            month = Double.parseDouble(jtxtMonth.getText());
            String Month = String.format(jtxtMonth.getText());

        }

        //////////////////////////Calculation //////////////////////////////

        payment = loan +((loan * interest)/100);

        Monthlypayment = payment/month;
        String PayMonth = String.format("% 2f", Monthlypayment);
        jtxtMonthlyPayment.setText(PayMonth);

        name = String.format(jtxtName.getText());
        address = String.format(jtxtAddress.getText());
        account = String.format(jtxtAccountType.getText());
        withdrawal = String.format(jWithdrawal.getText());
        deposite = String.format(jDeposite.getText());
        overdraft = String.format(jOverDraft.getText());

        //////////////////// Loan Report /////////////////////////////////////
        jLoanReport.append("\t\n Loan Management System :\n\n" +
            "\n\nCustomer Name : \t\t " + name +
            "\n\nCustomer Address : \t\t " + address +
            "\n\nAccount Type : \t\t\t " + account +
            "\n\nWithdrawal.? : \t\t\t " + withdrawal +
            "\n\nDeposite.? : \t\t\t " + deposite +
            "\n\nOverDraft.? : \t\t\t " + overdraft +
            "\n\nAmount Of Loan : \t\tRs " + loan +
            "\n\nNumber Of Payment :\t\t" + interest +
            "\n\nNumber Of Month For Payment : \t" + month +
            "\n\nPayment Per Month :  \t\tRs " + Monthlypayment +
            "\n\nTotal Loan Payment :  \t\tRs " + payment +
            "\n\n Thanks For Using D_R's Loan System");

    }//GEN-LAST:event_jloancalculatorActionPerformed

    private void jresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jresetActionPerformed

        jtxtLoan.setText("");
        jtxtInterest.setText("");
        jtxtMonth.setText("");
        jtxtName.setText("");
        jtxtAddress.setText("");
        jtxtAccountType.setText("");
        jWithdrawal.setText("");
        jDeposite.setText("");
        jOverDraft.setText("");
        jLoanReport.setText("");
        jtxtMonthlyPayment.setText("");
        jloantype.setText("");

    }//GEN-LAST:event_jresetActionPerformed

    private void jexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jexitActionPerformed
        ///////////////////////////////// Exit Button ////////////////////////
       My_Page mp = new My_Page();
       mp.setVisible(true);
       
    }//GEN-LAST:event_jexitActionPerformed

    private void jtxtMonthlyPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtMonthlyPaymentActionPerformed

    }//GEN-LAST:event_jtxtMonthlyPaymentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Loan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jDeposite;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextArea jLoanReport;
    private javax.swing.JTextField jOverDraft;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jWithdrawal;
    private javax.swing.JButton jexit;
    private javax.swing.JButton jloancalculator;
    private javax.swing.JTextField jloantype;
    private javax.swing.JButton jreset;
    private javax.swing.JTextField jtxtAccountType;
    private javax.swing.JTextField jtxtAddress;
    private javax.swing.JTextField jtxtInterest;
    private javax.swing.JTextField jtxtLoan;
    private javax.swing.JTextField jtxtMonth;
    private javax.swing.JTextField jtxtMonthlyPayment;
    private javax.swing.JTextField jtxtName;
    // End of variables declaration//GEN-END:variables
}
