/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.util.Random;
/**
 *
 * @author Dhaval
 */
public class New_Account extends javax.swing.JFrame {
Connection con;
PreparedStatement pst;
ResultSet rs;
    /**
     * Creates new form New_Account
     */
    public New_Account() {
        initComponents();
        Connect();
        RandomAcc();
        RandomMicr();
        RandomPin();
        Bal();
    }
    
    
    public void Connect()
    {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            try {
                con = DriverManager.getConnection("jdbc:mysql://localhost/online_system","root","");
            } catch (SQLException ex) {
                Logger.getLogger(New_Account.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(New_Account.class.getName()).log(Level.SEVERE, null, ex);
        }           
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jaccnumber2 = new javax.swing.JTextField();
        jmicr2 = new javax.swing.JTextField();
        jpin2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jaddress2 = new javax.swing.JTextArea();
        jname2 = new javax.swing.JTextField();
        jmobile2 = new javax.swing.JTextField();
        jamount2 = new javax.swing.JTextField();
        janswer2 = new javax.swing.JTextField();
        jnationality2 = new javax.swing.JComboBox();
        jacctype2 = new javax.swing.JComboBox();
        jmale2 = new javax.swing.JRadioButton();
        jfemale2 = new javax.swing.JRadioButton();
        jdob2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jquestion2 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.yellow, java.awt.Color.orange), "New_Account", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("MS Gothic", 1, 36), new java.awt.Color(102, 255, 51))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(102, 255, 51));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 255, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gender          :");

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 255, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Account Type    :");

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 255, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Address         :");

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 255, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText(" Pin            :");

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 255, 51));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Account Number  :");

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 255, 51));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("MICR Number     :");

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("MS Gothic", 1, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 255, 51));
        jButton1.setText("Create");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("MS Gothic", 1, 36)); // NOI18N
        jButton2.setForeground(new java.awt.Color(102, 255, 51));
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("MS Gothic", 1, 36)); // NOI18N
        jButton3.setForeground(new java.awt.Color(102, 255, 51));
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 255, 51));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText(" Answer           :");

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 255, 51));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Security Question :");

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 255, 51));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Mobile Number     :");

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 255, 51));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Name              :");

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 255, 51));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Date Of Birth     :");

        jLabel13.setBackground(new java.awt.Color(0, 0, 0));
        jLabel13.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 255, 51));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Nationality       :");

        jaccnumber2.setBackground(new java.awt.Color(0, 0, 0));
        jaccnumber2.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        jaccnumber2.setForeground(new java.awt.Color(102, 255, 51));
        jaccnumber2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jmicr2.setBackground(new java.awt.Color(0, 0, 0));
        jmicr2.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        jmicr2.setForeground(new java.awt.Color(102, 255, 51));
        jmicr2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jpin2.setBackground(new java.awt.Color(0, 0, 0));
        jpin2.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        jpin2.setForeground(new java.awt.Color(102, 255, 51));
        jpin2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jaddress2.setBackground(new java.awt.Color(0, 0, 0));
        jaddress2.setColumns(20);
        jaddress2.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        jaddress2.setForeground(new java.awt.Color(102, 255, 51));
        jaddress2.setRows(5);
        jScrollPane1.setViewportView(jaddress2);

        jname2.setBackground(new java.awt.Color(0, 0, 0));
        jname2.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        jname2.setForeground(new java.awt.Color(102, 255, 51));
        jname2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jmobile2.setBackground(new java.awt.Color(0, 0, 0));
        jmobile2.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        jmobile2.setForeground(new java.awt.Color(102, 255, 51));
        jmobile2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jamount2.setBackground(new java.awt.Color(0, 0, 0));
        jamount2.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        jamount2.setForeground(new java.awt.Color(102, 255, 51));
        jamount2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        janswer2.setBackground(new java.awt.Color(0, 0, 0));
        janswer2.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        janswer2.setForeground(new java.awt.Color(102, 255, 51));
        janswer2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jnationality2.setBackground(new java.awt.Color(0, 0, 0));
        jnationality2.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        jnationality2.setForeground(new java.awt.Color(102, 255, 51));
        jnationality2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Hindu", "Muslim", "Christian" }));
        jnationality2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnationality2ActionPerformed(evt);
            }
        });

        jacctype2.setBackground(new java.awt.Color(0, 0, 0));
        jacctype2.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        jacctype2.setForeground(new java.awt.Color(102, 255, 51));
        jacctype2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Savings", "Current" }));
        jacctype2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jacctype2ActionPerformed(evt);
            }
        });

        jmale2.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jmale2);
        jmale2.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        jmale2.setForeground(new java.awt.Color(102, 255, 51));
        jmale2.setText("Male");

        jfemale2.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jfemale2);
        jfemale2.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        jfemale2.setForeground(new java.awt.Color(102, 255, 51));
        jfemale2.setText("Female");

        jdob2.setBackground(new java.awt.Color(0, 0, 0));
        jdob2.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        jdob2.setForeground(new java.awt.Color(102, 255, 51));
        jdob2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 255, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Amount            :");

        jquestion2.setBackground(new java.awt.Color(0, 0, 0));
        jquestion2.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        jquestion2.setForeground(new java.awt.Color(153, 255, 51));
        jquestion2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "What is your Favorite Place?", "What Is Your Favorite Food?", " " }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jmicr2)
                            .addComponent(jpin2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                            .addComponent(jacctype2, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jmale2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jfemale2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jaccnumber2))
                        .addGap(115, 115, 115)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(janswer2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jmobile2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jnationality2, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jdob2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jname2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jamount2)
                            .addComponent(jquestion2, javax.swing.GroupLayout.Alignment.LEADING, 0, 387, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(261, 261, 261)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jaccnumber2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jmicr2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jdob2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jnationality2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jpin2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jmobile2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jacctype2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jname2, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(179, 179, 179)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jmale2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jfemale2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jquestion2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(janswer2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jamount2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    public void RandomAcc(){
        Random ra = new Random();
        jaccnumber2.setText(""+ra.nextInt(10000+1));
    }
    
    public void RandomMicr(){
        Random ra = new Random();
        jmicr2.setText(""+ra.nextInt(1000+1));
    }
    
    public void RandomPin(){
        Random ra = new Random();
        jpin2.setText(""+ra.nextInt(1000+1));
    }
    
    public void Bal(){
        
        String name = jname2.getText();
        String accnumber = jaccnumber2.getText();
        String micr = jmicr2.getText();
        String amount = jamount2.getText();
        
        //String sql="insert into balance(name,accnumber,micr,balance) values (?,?,?,?)";
        try{
            pst=con.prepareStatement("insert into balance(name,acc_number,micr,balance) values (?,?,?,?)");
            pst.setString(1, name);
            pst.setString(2, accnumber);
            pst.setString(3, micr);
            pst.setString(4, amount);
            pst.executeUpdate();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    
    
    private void jnationality2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jnationality2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jnationality2ActionPerformed

    private void jacctype2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jacctype2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jacctype2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        Login l = new Login();
        l.setVisible(true);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        jaccnumber2.setText("");
        jmicr2.setText("");
        jpin2.setText("");
        jacctype2.setSelectedItem("");
        jaccnumber2.setText("");
        jaddress2.setText("");
        jname2.setText("");
        jdob2.setText("");
        jnationality2.setSelectedItem("");
        jmobile2.setText("");
        jamount2.setText("");
        janswer2.setText("");
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
       // String sql="insert into bank(acc_number,mirc,pin,acc_type,gender,address,name,dob,nationality,mobile,question,answer,amount) values (?,?,?,?,?,?,?,?,?,?,?,?,?)";
        String accnumber = jaccnumber2.getText();
        String micr = jmicr2.getText();
        String pin = jpin2.getText();
        String old_pin = jpin2.getText();
        String acctype = jacctype2.getSelectedItem().toString();
        String address = jaddress2.getText();
        String name = jname2.getText();
        String dob = jdob2.getText();
        String nationality = jnationality2.getSelectedItem().toString();
        String mobile = jmobile2.getText();
        String question = jquestion2.getSelectedItem().toString();
        String answer = janswer2.getText();
        String amount = jamount2.getText();
        //String accnumber = jaccnumber2.getText();
        
        try{
            
            pst=con.prepareStatement("insert into bank(acc_number,micr,pin,acc_type,gender,address,name,dob,nationality,mobile_no,question,answer,amount,old_pin) values (?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
            pst.setString(1,accnumber);
            pst.setString(2,micr);
            pst.setString(3,pin);
            pst.setString(4,acctype);
            
            jmale2.setActionCommand("Male");
            jfemale2.setActionCommand("Female");
            pst.setString(5,buttonGroup1.getSelection().getActionCommand());
            
            pst.setString(6,address);
            pst.setString(7,name);
            pst.setString(8,dob);
            pst.setString(9,nationality);
            pst.setString(10,mobile);
            pst.setString(11,question);
            pst.setString(12,answer);
            pst.setString(13,amount);
            pst.setString(14,old_pin);
            int k = pst.executeUpdate();
            
            if(k==1)
            {
                JOptionPane.showMessageDialog(this,"Account Created");

        jaccnumber2.setText("");
        jmicr2.setText("");
        jpin2.setText("");
        jacctype2.setSelectedItem("");
        jaccnumber2.setText("");
        jaddress2.setText("");
        jname2.setText("");
        jdob2.setText("");
        jnationality2.setSelectedItem("");
        jmobile2.setText("");
        jamount2.setText("");
        janswer2.setText("");
                
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Error!");
            }
            
            //JOptionPane.showMessageDialog(null,"Account Created!");
            Bal();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(New_Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(New_Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(New_Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(New_Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new New_Account().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jaccnumber2;
    private javax.swing.JComboBox jacctype2;
    private javax.swing.JTextArea jaddress2;
    private javax.swing.JTextField jamount2;
    private javax.swing.JTextField janswer2;
    private javax.swing.JTextField jdob2;
    private javax.swing.JRadioButton jfemale2;
    private javax.swing.JRadioButton jmale2;
    private javax.swing.JTextField jmicr2;
    private javax.swing.JTextField jmobile2;
    private javax.swing.JTextField jname2;
    private javax.swing.JComboBox jnationality2;
    private javax.swing.JTextField jpin2;
    private javax.swing.JComboBox jquestion2;
    // End of variables declaration//GEN-END:variables
}
